server:
  port: 8080

spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
  datasource:
    url: jdbc:mysql://localhost:3306/molip
    driverClassName: com.mysql.cj.jdbc.Driver
    username: ${LOCAL_MYSQL_USERNAME:root}
    password: ${LOCAL_MYSQL_PASSWORD:00000000}


jwt:
  secret: ${JWT_SECRET:test-secret-key-test-secret-key-test-secret-key-test-secret-key}
  access-expiration-ms: ${ACCESS_EXPIRATION_MS:3600000}
  refresh-expiration-ms: ${REFRESH_EXPIRATION_MS:86400000}

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
    groups.enabled: true

  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    display-request-duration: true
    persistAuthorization: true